#pragma once

////////////////////////////////////////////////////////////////////////////////
// Enums.

#include "buffer/enum/shader_storage_buffer.hpp"
#include "shader/enum/compile_status.hpp"
#include "shader/enum/compute_shader.hpp"
#include "shader/enum/fragment_shader.hpp"
#include "shader/enum/info_log_length.hpp"
#include "shader/enum/vertex_shader.hpp"

////////////////////////////////////////////////////////////////////////////////
// Functions.

#include "buffer/function/core/bind_buffer.hpp"
#include "buffer/function/core/get_named_buffer_parameter_iv.hpp"
#include "buffer/function/core/named_buffer_storage.hpp"
#include "buffer/function/std/get_named_buffer_sub_data.hpp"
#include "buffer/function/std/named_buffer_storage.hpp"
// #include "buffer_mapping/function/core/map_named_buffer.hpp"
// #include "buffer_mapping/function/core/map_named_buffer_range.hpp"
#include "capability/function/disable.hpp"
#include "capability/function/enable.hpp"
#include "framebuffer/function/clear_named_framebuffer.hpp"
#include "program/function/core/attach_shader.hpp"
#include "program/function/core/get_attrib_location.hpp"
#include "program/function/core/get_uniform_location.hpp"
#include "program/function/core/link_program.hpp"
#include "program/function/core/use_program.hpp"
#include "program/function/ext/shader_storage_block_binding.hpp"
// #include "query/function/begin_query.hpp"
// #include "query/function/end_query.hpp"
// #include "query/function/get_query_object.hpp"
#include "shader/function/core/compile_shader.hpp"
#include "shader/function/core/create_shader.hpp"
#include "shader/function/core/get_shader_iv.hpp"
#include "shader/function/core/shader_source.hpp"
#include "shader/function/ext/get_shader_iv.hpp"
#include "shader/function/std/shader_source.hpp"
#include "vertex_array/function/core/bind_vertex_array.hpp"
#include "vertex_array/function/core/enable_vertex_array_attrib.hpp"
#include "vertex_array/function/core/vertex_array_attrib_binding.hpp"
#include "vertex_array/function/core/vertex_array_attrib_format.hpp"
#include "vertex_array/function/core/vertex_array_element_buffer.hpp"
#include "vertex_array/function/core/vertex_array_vertex_buffer.hpp"


////////////////////////////////////////////////////////////////////////////////
// Types.

#include "buffer/type/core/buffer_name.hpp"
#include "buffer/type/core/buffer_target.hpp"
#include "buffer/type/core/optional_buffer_name.hpp"
#include "buffer/type/ext/buffer_object.hpp"
// #include "buffer_mapping/type/core/buffer_mapping.hpp"
#include "capability/type/core/enabled_capability.hpp"
#include "capability/type/ext/scoped.hpp"
#include "capability/type/ext/scoped_capability.hpp"
#include "draw/draw_elements_indirect_command.hpp"
#include "framebuffer/type/framebuffer.hpp"
#include "program/type/core/attribute_location.hpp"
#include "program/type/core/optional_attribute_location.hpp"
#include "program/type/core/optional_program_name.hpp"
#include "program/type/core/optional_uniform_location.hpp"
#include "program/type/ext/program_object.hpp"
#include "query/type/query.hpp"
#include "sampler/type/sampler_object.hpp"
#include "shader/type/core/shader_name.hpp"
#include "shader/type/ext/compute_shader_object.hpp"
#include "shader/type/ext/fragment_shader_object.hpp"
#include "shader/type/ext/shader_object.hpp"
#include "shader/type/ext/vertex_shader_object.hpp"
#include "texture/type/texture_unit.hpp"
#include "vertex_array/type/core/optional_vertex_array_name.hpp"
#include "vertex_array/type/core/vertex_array_name.hpp"
#include "vertex_array/type/ext/vertex_array_object.hpp"
